cd /d "./create_table/"
python "./create_table_countries.py"
python "./create_table_directors.py"
python "./create_table_filmes.py"
python "./create_table_genres.py"
python "./create_table_languages.py"
python "./create_table_locations.py"
python "./create_table_stars.py"
python "./create_table_writers.py"
python "./create_table_writers_filmes.py"
python "./create_table_countries_filmes.py"
python "./create_table_directors_filmes.py"
python "./create_table_genres_filmes.py"
python "./create_table_languages_filmes.py"
python "./create_table_locations_filmes.py"
python "./create_table_stars_filmes.py"
#python "./create_table_stars_filmes2.py"
